export const SELECT_FLIGHTS = "SELECT_FLIGHT";
export const DISPLAY_FLIGHTS = "DISPLAY_FLIGHTS";
export const DISPLAY_FLIGHT_DETAILS = "DISPLAY_FLIGHT_DETAILS";
export const DISPLAY_PASSENGERS = "DISPLAY_PASSENGERS";
export const CHECK_IN_PASSENERS = "CHECKIN_PASSENERS";
export const UNDO_CHECK_IN_PASSENGERS = "UNDO_CHECK_IN_PASSENGERS";
