export const SELECT_FLIGHTS = "SELECT_FLIGHT";
export const DISPLAY_FLIGHTS = "DISPLAY_FLIGHTS";
export const DISPLAY_SEAT_DETAILS = "DISPLAY_SEAT_DETAILS";
export const DISPLAY_FLIGHT_DETAILS = "DISPLAY_FLIGHT_DETAILS";
export const CHECK_IN_PASSENGERS_SEAT = "CHECKIN_PASSENGERS_SEAT";
export const UNDO_CHECK_IN_PASSENGERS_SEAT = "UNDO_CHECK_IN_PASSENGERS";
