// export const DISPLAY_PASSENGERS = "DISPLAY_PASSENGERS";
// export const CHECKIN_PASSENGERS = "CHECKIN_PASSENGERS";

export const FETCH_PASSENGERS_DETAILS = "FETCH_PASSENGERS_DETAILS";
export const FETCH_PASSENGERS_SUCCESS = "FETCH_PASSENGERS_SUCCESS";
export const FETCH_PASSENGERS_FAILURE = "FETCH_PASSENGERS_FAILURE";

export const UPDATE_PASSENGER_CHECKIN_CHECKOUT =
  "UPDATE_PASSENGER_CHECKIN_CHECKOUT";
