export const FETCH_FLIGHT_DETAILS_BY_ID = "FETCH_FLIGHT_DETAILS_BY_ID";
export const FETCH_FLIGHT_DETAILS_BY_ID_SUCCESS =
  "FETCH_FLIGHT_DETAILS_BY_ID_SUCCESS";
export const FETCH_FLIGHT_DETAILS_BY_ID_FAILURE =
  "FETCH_FLIGHT_DETAILS_BY_ID_FAILURE";

export const FETCH_SEATS_DETAILS_BY_FLIGHT_ID =
  "FETCH_SEATS_DETAILS_BY_FLIGHT_ID";
export const FETCH_SEATS_DETAILS_BY_FLIGHT_ID_SUCCESS =
  "FETCH_SEATS_DETAILS_BY_FLIGHT_ID_SUCCESS";
export const FETCH_SEATS_DETAILS_BY_FLIGHT_ID_FAILURE =
  "FETCH_SEATS_DETAILS_BY_FLIGHT_ID_FAILURE";

export const UPDATE_CHECKIN_CHECKOUT = "UPDATE_CHECKIN_CHECKOUT";
export const UPDATE_CHECKIN_CHECKOUT_SUCCESS =
  "UPDATE_CHECKIN_CHECKOUT_SUCCESS";
export const UPDATE_CHECKIN_CHECKOUT_FAILURE =
  "UPDATE_CHECKIN_CHECKOUT_FAILURE";
